name: Sync Main with Child Branches

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Fetch All Branches
        run: git fetch --all

      - name: Merge Main into Child Branches
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          for branch in $(git for-each-ref --format='%(refname:lstrip=3)' refs/remotes/origin | grep -vE "^(main|HEAD)$"); do
            echo "Merging main into $branch..."
            git checkout $branch
            git merge origin/main --no-edit || echo "⚠️ Merge conflict in $branch, skipping..."
            git push https://x-access-token:$GH_PAT@github.com/omrmhd5/OSTR.git $branch || echo "❌ Push failed for $branch"
          done
